### ISSUE TITLE
missing.png is missing!

### ISSUE THREAD

**Issue by lzell** [OpenKit/openkit-server#2]
Copied from website feedback from Brandon:

Ironically http://stage.openkit.io/icons/original/missing.png is missing. If a leaderboard item without an image associated with it gets called the system attempts to pull http://stage.openkit.io/icons/original/missing.png. The problem is that this is missing which throws another exception. 

04-12 03:46:52.134: W/System.err(18885): java.io.FileNotFoundException: http://stage.openkit.io/icons/original/missing.png
04-12 03:46:52.144: W/System.err(18885): at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:521)
04-12 03:46:52.144: W/System.err(18885): at java.net.URLConnection$DefaultContentHandler.getContent(URLConnection.java:1087)
04-12 03:46:52.144: W/System.err(18885): at java.net.URLConnection.getContent(URLConnection.java:206)
04-12 03:46:52.144: W/System.err(18885): at io.openkit.smartimageview.WebImage.getBitmapFromUrl(WebImage.java:51)
04-12 03:46:52.144: W/System.err(18885): at io.openkit.smartimageview.WebImage.getBitmap(WebImage.java:34)
04-12 03:46:52.144: W/System.err(18885): at io.openkit.smartimageview.SmartImageTask.run(SmartImageTask.java:38)
04-12 03:46:52.144: W/System.err(18885): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
04-12 03:46:52.144: W/System.err(18885): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
04-12 03:46:52.144: W/System.err(18885): at java.lang.Thread.run(Thread.java:1019)

**Comment by hanrelan** [comment]
Ha!
